-- Stage 56: per-view server render duration
ALTER TABLE `PaketView` ADD COLUMN `renderMs` INT NULL;

-- Stage 56: LANDING_SLOW_OWNER enum value
ALTER TABLE `jemaahnotifpref` DROP PRIMARY KEY,
    MODIFY `type` ENUM('BOOKING_CREATED', 'PAYMENT_RECEIVED', 'BOOKING_LUNAS', 'REFUND_ISSUED', 'CANCEL_REQUESTED', 'PAYMENT_SETTLED_ADMIN', 'PAYOUT_CREATED', 'DOC_VERIFIED', 'INCIDENT_REPORTED', 'DAILY_DIGEST_OWNER', 'WEEKLY_DIGEST_OWNER', 'AGENT_WEEKLY_DIGEST', 'PAYOUT_REMINDER_OWNER', 'WAITLIST_SLOT_FREED', 'AGENT_STALLED_LEADS', 'TRAFFIC_ANOMALY_OWNER', 'LANDING_SLOW_OWNER', 'GENERIC') NOT NULL,
    ADD PRIMARY KEY (`jemaahId`, `type`);

ALTER TABLE `notification` MODIFY `type` ENUM('BOOKING_CREATED', 'PAYMENT_RECEIVED', 'BOOKING_LUNAS', 'REFUND_ISSUED', 'CANCEL_REQUESTED', 'PAYMENT_SETTLED_ADMIN', 'PAYOUT_CREATED', 'DOC_VERIFIED', 'INCIDENT_REPORTED', 'DAILY_DIGEST_OWNER', 'WEEKLY_DIGEST_OWNER', 'AGENT_WEEKLY_DIGEST', 'PAYOUT_REMINDER_OWNER', 'WAITLIST_SLOT_FREED', 'AGENT_STALLED_LEADS', 'TRAFFIC_ANOMALY_OWNER', 'LANDING_SLOW_OWNER', 'GENERIC') NOT NULL;
