-- Stage 276 — add DOC_VERIFY_SLA_ADMIN to NotificationType enum.
-- Daily digest of SUBMITTED docs > 48h awaiting staff verification.
ALTER TABLE `Notification`
  MODIFY COLUMN `type` ENUM(
    'BOOKING_CREATED', 'PAYMENT_RECEIVED', 'BOOKING_LUNAS', 'REFUND_ISSUED',
    'CANCEL_REQUESTED', 'PAYMENT_SETTLED_ADMIN', 'PAYOUT_CREATED', 'DOC_VERIFIED',
    'INCIDENT_REPORTED', 'DAILY_DIGEST_OWNER', 'WEEKLY_DIGEST_OWNER',
    'AGENT_WEEKLY_DIGEST', 'PAYOUT_REMINDER_OWNER', 'WAITLIST_SLOT_FREED',
    'AGENT_STALLED_LEADS', 'TRAFFIC_ANOMALY_OWNER', 'LANDING_SLOW_OWNER',
    'CREW_WEEKLY_DIGEST', 'TESTIMONIAL_PUBLISHED', 'FIRST_PAYMENT_THANKS',
    'INCIDENT_ESCALATED', 'BOOKING_NOTE_MENTION', 'INCIDENT_SLA_BREACH_OWNER',
    'TASK_OVERDUE_ESCALATION', 'API_KEY_SCOPE_DOWN_OWNER', 'WEBHOOK_HEALTH_OWNER',
    'MANIFEST_CLOSE_NUDGE', 'KOMISI_STATEMENT_READY', 'AGENT_ANNUAL_RECAP',
    'STATEMENT_UNREAD_NUDGE', 'PAYMENT_REMINDER', 'DOC_EXPIRING_SOON',
    'PASSPORT_RENEWAL_REMINDER', 'CREW_DIETARY_BRIEF', 'PICKUP_REMINDER',
    'INSTALLMENT_OVERDUE_ADMIN', 'DOC_VERIFY_SLA_ADMIN',
    'GENERIC'
  ) NOT NULL;
