// Stage 79/85 — per-(type, channel) CTR over a rolling window.
//
// CTR = unique-click rate, computed as:
//   - sent      = count(Notification where status=SENT in window)
//   - clicked   = count(Notification with at least one EmailClick row)
//   - ctrPct    = clicked / sent × 100
//
// S85 — channels now include WA. The EmailClick model carries clicks
// for both channels (since /r/<token> is channel-agnostic); the model
// name is historical and isn't renamed to keep migration risk low.
//
// Why unique-click and not raw click volume:
//   - One recipient clicking the link 5 times shouldn't read as "500% CTR"
//   - Marketing teams think in terms of "did the recipient engage" not
//     "how many tabs did they open"
//
// Excluded:
//   - SKIPPED / PENDING / FAILED rows (denominator = SENT only)
//   - Channels other than EMAIL / WA (CONSOLE never goes out to a recipient)
//   - Combos with <5 SENT in window (sample too small to declare CTR;
//     marked `lowSample: true` so view can dim them)

import { db } from './../lib/db.js';

const ONE_DAY_MS = 86_400_000;
const DEFAULT_CHANNELS = ['EMAIL', 'WA'];

export async function getEmailCtrByType({ now = new Date(), days = 30, channels = DEFAULT_CHANNELS } = {}) {
  const start = new Date(now.getTime() - days * ONE_DAY_MS);
  start.setHours(0, 0, 0, 0);
  const end = new Date(now);
  end.setHours(0, 0, 0, 0);
  end.setTime(end.getTime() + ONE_DAY_MS);

  // SENT counts per (type, channel). groupBy is fastest here.
  const sentRows = await db.notification.groupBy({
    by: ['type', 'channel'],
    where: {
      channel: { in: channels },
      status: 'SENT',
      sentAt: { gte: start, lt: end },
    },
    _count: { _all: true },
  });
  if (sentRows.length === 0) {
    return { rows: [], windowDays: days, channels, totals: { sent: 0, clicked: 0, ctrPct: null } };
  }
  // Key is `${type}::${channel}` so the same type across channels stays distinct.
  const sentByKey = new Map(sentRows.map((r) => [`${r.type}::${r.channel}`, r._count._all]));

  // Clicked counts per (type, channel) — same predicate path as S79.
  const clickedRows = await db.notification.groupBy({
    by: ['type', 'channel'],
    where: {
      channel: { in: channels },
      status: 'SENT',
      sentAt: { gte: start, lt: end },
      clicks: { some: {} },
    },
    _count: { _all: true },
  });
  const clickedByKey = new Map(clickedRows.map((r) => [`${r.type}::${r.channel}`, r._count._all]));

  const rows = [...sentByKey.entries()]
    .map(([key, sent]) => {
      const [type, channel] = key.split('::');
      const clicked = clickedByKey.get(key) || 0;
      const ctrPct = sent > 0 ? Math.round((clicked / sent) * 1000) / 10 : null;
      return {
        type,
        channel,
        sent,
        clicked,
        ctrPct,
        lowSample: sent < 5,
      };
    })
    // Default sort: highest sample first so admin sees the most reliable
    // numbers at the top. Tie-break by type+channel for stability.
    .sort((a, b) => b.sent - a.sent || a.type.localeCompare(b.type) || a.channel.localeCompare(b.channel));

  const totalSent = rows.reduce((s, r) => s + r.sent, 0);
  const totalClicked = rows.reduce((s, r) => s + r.clicked, 0);
  const overallCtr = totalSent > 0
    ? Math.round((totalClicked / totalSent) * 1000) / 10
    : null;

  return {
    rows,
    windowDays: days,
    channels,
    totals: { sent: totalSent, clicked: totalClicked, ctrPct: overallCtr },
  };
}

/**
 * Stage 84 — per-URL click heatmap for a single notif type.
 *
 * Answers "which CTA in the email body is doing the work" — type-level CTR
 * (S79) is too coarse when an email has multiple links (e.g. WEEKLY_DIGEST
 * has /admin AND deep links to each paket). A 30% CTR on the type doesn't
 * tell you whether it was the main CTA or a footer link.
 *
 * Heatmap normalises absolute URLs to their path (drops scheme + host +
 * query) so links generated by different env hosts collapse to the same
 * row. Long paths truncated to 80 chars in the label so the table doesn't
 * blow out horizontally.
 *
 * Returns rows sorted by `clicks` desc — biggest mover first. Includes
 * `sharePct` (per-URL ÷ total clicks for this type) so admin sees relative
 * weight, not just raw numbers.
 */
export async function getEmailClickHeatmap({ type, channel = null, now = new Date(), days = 30 } = {}) {
  if (!type) return { type: null, channel, rows: [], totals: { clicks: 0, urls: 0 } };
  const start = new Date(now.getTime() - days * ONE_DAY_MS);
  start.setHours(0, 0, 0, 0);
  const end = new Date(now);
  end.setHours(0, 0, 0, 0);
  end.setTime(end.getTime() + ONE_DAY_MS);

  // Pull EmailClick rows joined back through Notification → type filter.
  // No groupBy here because we want to aggregate AFTER URL normalisation
  // (groupBy in Prisma is by exact column, not by a derived value).
  // Type is a Prisma enum — an unknown string throws "Invalid value for
  // argument `type`". Wrap so callers can pass a bookmarked-but-since-
  // renamed type without a 500.
  //
  // S85 — optional `channel` narrows the lens. Null channel = both EMAIL
  // and WA combined (useful for the type-only drill from the panel link).
  const notifFilter = {
    type,
    sentAt: { gte: start, lt: end },
    channel: channel ? channel : { in: DEFAULT_CHANNELS },
  };
  let clicks;
  try {
    clicks = await db.emailClick.findMany({
      where: { notification: notifFilter },
      select: { targetUrl: true, clickCount: true },
    });
  } catch (err) {
    if (String(err?.message || '').includes('Invalid value for argument `type`')) {
      return { type, channel, rows: [], totals: { clicks: 0, urls: 0 }, windowDays: days };
    }
    throw err;
  }
  if (clicks.length === 0) {
    return { type, channel, rows: [], totals: { clicks: 0, urls: 0 }, windowDays: days };
  }

  // Normalise: keep path (+ query for /r/ wrapped urls already unwrapped at
  // store-time). Strip scheme + host so http://prod.example.com/admin and
  // http://localhost:3001/admin collapse to /admin.
  function normalise(url) {
    try {
      // Absolute URL — strip scheme + host
      const u = new URL(url);
      return u.pathname + (u.search || '');
    } catch (_e) {
      // Already a path or malformed — pass through
      return url;
    }
  }

  const byUrl = new Map();   // normalised → { clicks, recipients }
  for (const c of clicks) {
    const key = normalise(c.targetUrl);
    const prev = byUrl.get(key) || { clicks: 0, recipients: 0 };
    prev.clicks += c.clickCount || 1;
    prev.recipients += 1;   // one EmailClick row = one notif → one recipient
    byUrl.set(key, prev);
  }

  const totalClicks = Array.from(byUrl.values()).reduce((s, v) => s + v.clicks, 0);
  const rows = Array.from(byUrl.entries())
    .map(([url, v]) => ({
      url,
      label: url.length > 80 ? url.slice(0, 77) + '…' : url,
      clicks: v.clicks,
      recipients: v.recipients,
      sharePct: totalClicks > 0
        ? Math.round((v.clicks / totalClicks) * 1000) / 10
        : null,
    }))
    .sort((a, b) => b.clicks - a.clicks || a.url.localeCompare(b.url));

  return {
    type,
    channel,
    rows,
    totals: { clicks: totalClicks, urls: rows.length },
    windowDays: days,
  };
}
