-- Stage 70: TESTIMONIAL_PUBLISHED enum value
ALTER TABLE `jemaahnotifpref` DROP PRIMARY KEY,
    MODIFY `type` ENUM('BOOKING_CREATED', 'PAYMENT_RECEIVED', 'BOOKING_LUNAS', 'REFUND_ISSUED', 'CANCEL_REQUESTED', 'PAYMENT_SETTLED_ADMIN', 'PAYOUT_CREATED', 'DOC_VERIFIED', 'INCIDENT_REPORTED', 'DAILY_DIGEST_OWNER', 'WEEKLY_DIGEST_OWNER', 'AGENT_WEEKLY_DIGEST', 'PAYOUT_REMINDER_OWNER', 'WAITLIST_SLOT_FREED', 'AGENT_STALLED_LEADS', 'TRAFFIC_ANOMALY_OWNER', 'LANDING_SLOW_OWNER', 'CREW_WEEKLY_DIGEST', 'TESTIMONIAL_PUBLISHED', 'GENERIC') NOT NULL,
    ADD PRIMARY KEY (`jemaahId`, `type`);

ALTER TABLE `notification` MODIFY `type` ENUM('BOOKING_CREATED', 'PAYMENT_RECEIVED', 'BOOKING_LUNAS', 'REFUND_ISSUED', 'CANCEL_REQUESTED', 'PAYMENT_SETTLED_ADMIN', 'PAYOUT_CREATED', 'DOC_VERIFIED', 'INCIDENT_REPORTED', 'DAILY_DIGEST_OWNER', 'WEEKLY_DIGEST_OWNER', 'AGENT_WEEKLY_DIGEST', 'PAYOUT_REMINDER_OWNER', 'WAITLIST_SLOT_FREED', 'AGENT_STALLED_LEADS', 'TRAFFIC_ANOMALY_OWNER', 'LANDING_SLOW_OWNER', 'CREW_WEEKLY_DIGEST', 'TESTIMONIAL_PUBLISHED', 'GENERIC') NOT NULL;

-- Stage 70: Testimonial.submittedByUserId
ALTER TABLE `Testimonial` ADD COLUMN `submittedByUserId` VARCHAR(191) NULL;
CREATE INDEX `Testimonial_submittedByUserId_idx` ON `Testimonial`(`submittedByUserId`);
ALTER TABLE `Testimonial` ADD CONSTRAINT `Testimonial_submittedByUserId_fkey`
  FOREIGN KEY (`submittedByUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- Stage 71: CrewProfile public fields
ALTER TABLE `crewprofile`
  ADD COLUMN `slug` VARCHAR(120) NULL,
  ADD COLUMN `titlePrefix` VARCHAR(40) NULL,
  ADD COLUMN `bio` TEXT NULL,
  ADD COLUMN `photoUrl` VARCHAR(255) NULL;
CREATE UNIQUE INDEX `CrewProfile_slug_key` ON `crewprofile`(`slug`);
