-- Stage 257 — booking group key. Tags related bookings (family,
-- company group, etc.) so admin can filter manifest by group + see
-- siblings on booking-detail. Auto-generated by S256 clone; admin can
-- type a value manually on the walk-in create form. NULL = ungrouped.
-- Indexed for the manifest filter scan.
ALTER TABLE `Booking`
  ADD COLUMN `groupKey` VARCHAR(40) NULL,
  ADD INDEX `Booking_groupKey_idx` (`groupKey`);
