-- Stage 75: FIRST_PAYMENT_THANKS enum
ALTER TABLE `jemaahnotifpref` DROP PRIMARY KEY,
    MODIFY `type` ENUM('BOOKING_CREATED', 'PAYMENT_RECEIVED', 'BOOKING_LUNAS', 'REFUND_ISSUED', 'CANCEL_REQUESTED', 'PAYMENT_SETTLED_ADMIN', 'PAYOUT_CREATED', 'DOC_VERIFIED', 'INCIDENT_REPORTED', 'DAILY_DIGEST_OWNER', 'WEEKLY_DIGEST_OWNER', 'AGENT_WEEKLY_DIGEST', 'PAYOUT_REMINDER_OWNER', 'WAITLIST_SLOT_FREED', 'AGENT_STALLED_LEADS', 'TRAFFIC_ANOMALY_OWNER', 'LANDING_SLOW_OWNER', 'CREW_WEEKLY_DIGEST', 'TESTIMONIAL_PUBLISHED', 'FIRST_PAYMENT_THANKS', 'GENERIC') NOT NULL,
    ADD PRIMARY KEY (`jemaahId`, `type`);

ALTER TABLE `notification` MODIFY `type` ENUM('BOOKING_CREATED', 'PAYMENT_RECEIVED', 'BOOKING_LUNAS', 'REFUND_ISSUED', 'CANCEL_REQUESTED', 'PAYMENT_SETTLED_ADMIN', 'PAYOUT_CREATED', 'DOC_VERIFIED', 'INCIDENT_REPORTED', 'DAILY_DIGEST_OWNER', 'WEEKLY_DIGEST_OWNER', 'AGENT_WEEKLY_DIGEST', 'PAYOUT_REMINDER_OWNER', 'WAITLIST_SLOT_FREED', 'AGENT_STALLED_LEADS', 'TRAFFIC_ANOMALY_OWNER', 'LANDING_SLOW_OWNER', 'CREW_WEEKLY_DIGEST', 'TESTIMONIAL_PUBLISHED', 'FIRST_PAYMENT_THANKS', 'GENERIC') NOT NULL;
