-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('BOOKING_CREATED', 'PAYMENT_RECEIVED', 'BOOKING_LUNAS', 'REFUND_ISSUED', 'CANCEL_REQUESTED', 'PAYOUT_CREATED', 'DOC_VERIFIED', 'GENERIC') NOT NULL;
